# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create([
  {email: 'kasumitoyama@cable.com', username: 'Kasumi!', password: 'password'},
  {email: 'taehanazono@cable.com', username: 'Usagi', password: 'Oddeye'},
  {email: 'rimiushigome@cable.com', username: 'ChocoCornetLove', password: 'YamabukiBakery'},
  {email: 'saayayamabuki@cable.com', username: 'Saaya', password: 'BreadforDin'},
  {email: 'arisaichigaya@cable.com', username: 'Arisa Ichigaya', password: 'thisisdumb'},
  {email: 'yukinaminato@cable.com', username: 'Lonewolf', password: 'LOUDER'},
  {email: 'sayohikawa@cable.com', username: 'Sayo Hikawa', password: 'friesfordays'},
  {email: 'lisaimai@cable.com', username: 'Lisa', password: 'mysongforyou'},
  {email: 'akoudagawa@cable.com', username: 'Demonic Drummer', password: 'TomoeIsTheCoolest'},
  {email: 'rinkoshirokane@cable.com', username: 'Rinrin', password: 'sevennotestogo'},
  {email: 'ranmitake@cable.com', username: 'AG Ran', password: 'sameasalways'},
  {email: 'mocaaoba@cable.com', username: 'Breadwinner', password: 'breadgoesin'},
  {email: 'himariuehara@cable.com', username: 'The Leader', password: 'heyheyhoh'},
  {email: 'tomoeudagawa@cable.com', username: 'BeatTheRain', password: 'SOOIIIYAAAA'},
  {email: 'tsugumihazawa@cable.com', username: 'A Cup of Stars', password: 'driftinginthesky'},
  {email: 'kokorotsurumaki@cable.com', username: 'Have You Smile!', password: 'hellohappyhellohappyhelloha'},
  {email: 'kaoruseta@cable.com', username: 'Hakanai', password: 'howfleeting'},
  {email: 'hagumikitazawa@cable.com', username: 'Croquette Dealah', password: 'meatmeinthemorning'},
  {email: 'kanonmatsubara@cable.com', username: 'Jellyfish Blob', password: 'fueefueejelly'},
  {email: 'misakiokusawa@cable.com', username: 'Misaki', password: 'crochetkeyboard'},
  {email: 'michelle@cable.com', username: 'DJ Bearbear', password: 'smiletoomisaki'},
  {email: 'ayamaruyama@cable.com', username: 'Undercover Idol', password: 'selfiestick'},
  {email: 'hinahikawa@cable.com', username: 'Boppin!', password: 'iloveyousayo'},
  {email: 'chisatoshirasagi@cable.com', username: 'C.Shirasagi', password: 'leonsundays'},
  {email: 'mayayamato@cable.com', username: 'Huhehe', password: 'technicdream'},
  {email: 'evewakamiya@cable.com', username: 'SakuraSamurai', password: 'bushibushido'}
])

Server.create([
  {name: 'Ryuseido', admin_id: 5},
  {name: 'Hanasakigawa Academy', admin_id: 7},
  {name: 'Haneoka Academy', admin_id: 23},
  {name: 'Yamabuki Bakery', admin_id: 4},
  {name: 'Kitazawa Croquettes', admin_id: 18},
  {name: 'CiRCLE', admin_id: 2}
])

Membership.create([
  {user_id: 1, server_id: 1},
  {user_id: 2, server_id: 1},
  {user_id: 3, server_id: 1},
  {user_id: 4, server_id: 1},
  {user_id: 5, server_id: 1},
  {user_id: 1, server_id: 2},
  {user_id: 2, server_id: 2},
  {user_id: 3, server_id: 2},
  {user_id: 4, server_id: 2},
  {user_id: 5, server_id: 2},
  {user_id: 7, server_id: 2},
  {user_id: 10, server_id: 2},
  {user_id: 16, server_id: 2},
  {user_id: 18, server_id: 2},
  {user_id: 19, server_id: 2},
  {user_id: 20, server_id: 2},
  {user_id: 22, server_id: 2},
  {user_id: 24, server_id: 2},
  {user_id: 26, server_id: 2},
  {user_id: 6, server_id: 3},
  {user_id: 8, server_id: 3},
  {user_id: 9, server_id: 3},
  {user_id: 11, server_id: 3},
  {user_id: 12, server_id: 3},
  {user_id: 13, server_id: 3},
  {user_id: 14, server_id: 3},
  {user_id: 15, server_id: 3},
  {user_id: 17, server_id: 3},
  {user_id: 23, server_id: 3},
  {user_id: 25, server_id: 3},
  {user_id: 4, server_id: 4},
  {user_id: 1, server_id: 4},
  {user_id: 2, server_id: 4},
  {user_id: 3, server_id: 4},
  {user_id: 5, server_id: 4},
  {user_id: 12, server_id: 4},
  {user_id: 18, server_id: 4},
  {user_id: 18, server_id: 5},
  {user_id: 1, server_id: 5},
  {user_id: 4, server_id: 5},
  {user_id: 16, server_id: 5},
  {user_id: 17, server_id: 5},
  {user_id: 19, server_id: 5},
  {user_id: 20, server_id: 5},
  {user_id: 21, server_id: 5},
  {user_id: 1, server_id: 6},
  {user_id: 2, server_id: 6},
  {user_id: 3, server_id: 6},
  {user_id: 4, server_id: 6},
  {user_id: 5, server_id: 6},
  {user_id: 6, server_id: 6},
  {user_id: 7, server_id: 6},
  {user_id: 8, server_id: 6},
  {user_id: 9, server_id: 6},
  {user_id: 10, server_id: 6},
  {user_id: 11, server_id: 6},
  {user_id: 12, server_id: 6},
  {user_id: 13, server_id: 6},
  {user_id: 14, server_id: 6},
  {user_id: 15, server_id: 6},
  {user_id: 16, server_id: 6},
  {user_id: 17, server_id: 6},
  {user_id: 18, server_id: 6},
  {user_id: 19, server_id: 6},
  {user_id: 20, server_id: 6},
  {user_id: 21, server_id: 6},
  {user_id: 22, server_id: 6},
  {user_id: 23, server_id: 6},
  {user_id: 24, server_id: 6},
  {user_id: 25, server_id: 6},
  {user_id: 26, server_id: 6},
])

Channel.create([
  {name: 'antique-shop', server_id: 1},
  {name: 'basement', server_id: 1},
  {name: 'bedroom', server_id: 1},
  {name: 'garden', server_id: 1},
  {name: 'classroom', server_id: 2},
  {name: 'restroom', server_id: 2},
  {name: 'gym', server_id: 2},
  {name: 'entry', server_id: 2},
  {name: 'council-room', server_id: 2},
  {name: 'classroom', server_id: 3},
  {name: 'restroom', server_id: 3},
  {name: 'gym', server_id: 3},
  {name: 'entry', server_id: 3},
  {name: 'council-room', server_id: 3},
  {name: 'bakery', server_id: 4},
  {name: 'bedroom', server_id: 4},
  {name: 'meat-shop', server_id: 5},
  {name: 'bedroom', server_id: 5},
  {name: 'cafeteria', server_id: 6},
  {name: 'stage', server_id: 6},
  {name: 'studio', server_id: 6},
  {name: 'store', server_id: 6}
])

Message.create([
  {body: 'Ariiiisaaaa!', author_id: 1, channel_id: 1},
  {body: 'AriiiisaaaaaAAAAA??!', author_id: 1, channel_id: 2},
  {body: 'Ariisa!', author_id: 1, channel_id: 3},
  {body: 'Arisa.', author_id: 1, channel_id: 4},
  {body: 'WHAT?!!', author_id: 5, channel_id: 4},
  {body: 'Ariisaaa, I was looking for you!', author_id: 1, channel_id: 4},
  {body: 'Do you not have a PHONE?', author_id: 5, channel_id: 4},
  {body: 'I do! I\'m using it to talk to you right now!', author_id: 1, channel_id: 4},
  {body: 'Hi!', author_id: 2, channel_id: 4},
  {body: 'Ohmygod.', author_id: 5, channel_id: 4},
  {body: 'O-Taeee!', author_id: 1, channel_id: 4},
  {body: 'I\'m going to bed.', author_id: 2, channel_id: 4},
  {body: 'O-Kaee, good night!!', author_id: 1, channel_id: 4},
  {body: 'I\'m in bed.', author_id: 2, channel_id: 3},
  {body: 'You don\'t have to say that, just go to sleep!', author_id: 2, channel_id: 3},
  {body: 'Oh my, are we having a sleepover?', author_id: 4, channel_id: 3},
  {body: 'I never said anything about that!', author_id: 5, channel_id: 3},
  {body: 'Arisa, what\'s up??', author_id: 1, channel_id: 4},
  {body: 'We haven\'t had a sleepover in a while!', author_id: 3, channel_id: 3},
  {body: 'This isn\'t a sleepover, it\'s a chatroom!', author_id: 5, channel_id: 3},
  {body: 'Ariisaa, stop ignoring me!', author_id: 1, channel_id: 4},
  {body: 'Yeah, let\'s do it again!', author_id: 2, channel_id: 3},
  {body: 'I\'m not ignoring you! Apparently everyone\'s sleeping in the #bedroom now..', author_id: 5, channel_id: 4},
  {body: 'Oh, so this is a sleepover!', author_id: 1, channel_id: 3},
  {body: 'This isn\'t a sleepover, it\'s a chatroom!', author_id: 5, channel_id: 3},
  {body: 'Where should we have the sleepover?', author_id: 4, channel_id: 3},
  {body: 'At Arisa\'s, of course! Just like always!!', author_id: 1, channel_id: 3},
  {body: 'Don\'t just go deciding that on your own!', author_id: 5, channel_id: 3},
  {body: 'Arisa, would you be okay with us spending a night? O-Tae, what do you think?', author_id: 4, channel_id: 3},
  {body: 'I\'m sleeping.', author_id: 2, channel_id: 3},
  {body: 'You\'re not sleeping! Go to actual sleep!', author_id: 5, channel_id: 3},
  {body: 'I just called your grandma, and she says it\'s okay to sleepover.', author_id: 2, channel_id: 3},
  {body: 'Ohh, thank you O-Taee!', author_id: 1, channel_id: 3},
  {body: 'Why do you have my grandma\'s number?!', author_id: 5, channel_id: 3},
  {body: 'Hooray! Thank you O-Tae!!', author_id: 3, channel_id: 3},
  {body: 'Good call, O-Tae!', author_id: 4, channel_id: 3},
  {body: 'Ugh, I\'m so done with all of you.', author_id: 5, channel_id: 3},
])

Role.create([
  {name: 'admin', server_id: 1},
  {name: 'user', server_id: 1},
  {name: 'admin', server_id: 2},
  {name: 'user', server_id: 2},
  {name: 'admin', server_id: 3},
  {name: 'user', server_id: 3},
  {name: 'admin', server_id: 4},
  {name: 'user', server_id: 4},
  {name: 'admin', server_id: 5},
  {name: 'user', server_id: 5},
  {name: 'admin', server_id: 6},
  {name: 'user', server_id: 6}
])

Permission.create([
  {role_id: 1, channel_id: 1},
  {role_id: 1, channel_id: 2},
  {role_id: 1, channel_id: 3},
  {role_id: 1, channel_id: 4},
  {role_id: 2, channel_id: 1},
  {role_id: 2, channel_id: 2},
  {role_id: 2, channel_id: 3},
  {role_id: 2, channel_id: 4},
  {role_id: 3, channel_id: 5},
  {role_id: 3, channel_id: 6},
  {role_id: 3, channel_id: 7},
  {role_id: 3, channel_id: 8},
  {role_id: 3, channel_id: 9},
  {role_id: 4, channel_id: 5},
  {role_id: 4, channel_id: 6},
  {role_id: 4, channel_id: 7},
  {role_id: 4, channel_id: 8},
  {role_id: 4, channel_id: 9},
  {role_id: 5, channel_id: 10},
  {role_id: 5, channel_id: 11},
  {role_id: 5, channel_id: 12},
  {role_id: 5, channel_id: 13},
  {role_id: 5, channel_id: 14},
  {role_id: 6, channel_id: 10},
  {role_id: 6, channel_id: 11},
  {role_id: 6, channel_id: 12},
  {role_id: 6, channel_id: 13},
  {role_id: 6, channel_id: 14},
  {role_id: 7, channel_id: 15},
  {role_id: 7, channel_id: 16},
  {role_id: 8, channel_id: 15},
  {role_id: 8, channel_id: 16},
  {role_id: 9, channel_id: 17},
  {role_id: 9, channel_id: 18},
  {role_id: 10, channel_id: 17},
  {role_id: 10, channel_id: 18},
  {role_id: 11, channel_id: 19},
  {role_id: 11, channel_id: 20},
  {role_id: 11, channel_id: 21},
  {role_id: 11, channel_id: 22},
  {role_id: 12, channel_id: 19},
  {role_id: 12, channel_id: 20},
  {role_id: 12, channel_id: 21},
  {role_id: 12, channel_id: 22}
])

UserRole.create([
  {user_id: 5, role_id: 1},
  {user_id: 1, role_id: 2},
  {user_id: 2, role_id: 2},
  {user_id: 3, role_id: 2},
  {user_id: 4, role_id: 2},
  {user_id: 7, role_id: 3},
  {user_id: 1, role_id: 4},
  {user_id: 2, role_id: 4},
  {user_id: 3, role_id: 4},
  {user_id: 4, role_id: 4},
  {user_id: 5, role_id: 4},
  {user_id: 10, role_id: 4},
  {user_id: 16, role_id: 4},
  {user_id: 18, role_id: 4},
  {user_id: 19, role_id: 4},
  {user_id: 20, role_id: 4},
  {user_id: 22, role_id: 4},
  {user_id: 24, role_id: 4},
  {user_id: 26, role_id: 4},
  {user_id: 23, role_id: 5},
  {user_id: 6, role_id: 6},
  {user_id: 8, role_id: 6},
  {user_id: 9, role_id: 6},
  {user_id: 11, role_id: 6},
  {user_id: 12, role_id: 6},
  {user_id: 13, role_id: 6},
  {user_id: 14, role_id: 6},
  {user_id: 15, role_id: 6},
  {user_id: 17, role_id: 6},
  {user_id: 25, role_id: 6},
  {user_id: 4, role_id: 7},
  {user_id: 1, role_id: 8},
  {user_id: 2, role_id: 8},
  {user_id: 3, role_id: 8},
  {user_id: 5, role_id: 8},
  {user_id: 12, role_id: 8},
  {user_id: 18, role_id: 8},
  {user_id: 18, role_id: 9},
  {user_id: 18, role_id: 10},
  {user_id: 1, role_id: 10},
  {user_id: 4, role_id: 10},
  {user_id: 16, role_id: 10},
  {user_id: 17, role_id: 10},
  {user_id: 19, role_id: 10},
  {user_id: 20, role_id: 10},
  {user_id: 21, role_id: 10},
  {user_id: 2, role_id: 11},
  {user_id: 1, role_id: 12},
  {user_id: 3, role_id: 12},
  {user_id: 4, role_id: 12},
  {user_id: 5, role_id: 12},
  {user_id: 6, role_id: 12},
  {user_id: 7, role_id: 12},
  {user_id: 8, role_id: 12},
  {user_id: 9, role_id: 12},
  {user_id: 10, role_id: 12},
  {user_id: 11, role_id: 12},
  {user_id: 12, role_id: 12},
  {user_id: 13, role_id: 12},
  {user_id: 14, role_id: 12},
  {user_id: 15, role_id: 12},
  {user_id: 16, role_id: 12},
  {user_id: 17, role_id: 12},
  {user_id: 18, role_id: 12},
  {user_id: 19, role_id: 12},
  {user_id: 20, role_id: 12},
  {user_id: 21, role_id: 12},
  {user_id: 22, role_id: 12},
  {user_id: 23, role_id: 12},
  {user_id: 24, role_id: 12},
  {user_id: 25, role_id: 12},
  {user_id: 26, role_id: 12},
])